<?xml version="1.0"?>
<package format="3">
  <name>memory_manager</name>
  <version>0.1.0</version>
  <description>ORKA ROS2 memory manager services.</description>
  <maintainer email="kai@example.com">kai</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>memory_manager_interfaces</depend>

  <exec_depend>python3-yaml</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
